function Rf = Rotate(r,p,ya)
%Rotate
%    Rf = Rotate(R,P,YA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Apr-2023 11:27:17

t2 = cos(p);
t3 = cos(r);
t4 = cos(ya);
t5 = sin(p);
t6 = sin(r);
t7 = sin(ya);
Rf = reshape([t2.*t4,t2.*t7,-t5,-t3.*t7+t4.*t5.*t6,t3.*t4+t5.*t6.*t7,t2.*t6,t6.*t7+t3.*t4.*t5,-t4.*t6+t3.*t5.*t7,t2.*t3],[3,3]);
