function T = TransRot(r,p,ya,x,y,z)
%TransRot
%    T = TransRot(R,P,YA,X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Apr-2023 20:02:04

t2 = cos(p);
t3 = cos(r);
t4 = cos(ya);
t5 = sin(p);
t6 = sin(r);
t7 = sin(ya);
T = reshape([t2.*t4,t2.*t7,-t5,0.0,-t3.*t7+t4.*t5.*t6,t3.*t4+t5.*t6.*t7,t2.*t6,0.0,t6.*t7+t3.*t4.*t5,-t4.*t6+t3.*t5.*t7,t2.*t3,0.0,x,y,z,1.0],[4,4]);
